version: '3'

services:
  postgres:
    image: postgres:16
    container_name: gearglobe-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gearglobe_database
      POSTGRES_USER: gearglobe
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gearglobe-network
  keycloak-dev:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak-dev-container
    ports:
      - "8443:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://gearglobe-postgres-container:5432/gearglobe_database
      KC_DB_USERNAME: gearglobe
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HOSTNAME_STRICT: false
    depends_on:
      - postgres
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - gearglobe-network

networks:
  gearglobe-network:
    driver: bridge

volumes:
  postgres-data:
  keycloak-data: