version: '3'

services:
  app-dev:
    container_name: gearglobe_app_dev
    image: gearglobe_app/dev:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gearglobe_db_dev:5432/gearglobe_db
      - SPRING_DATASOURCE_USERNAME=gearglobe
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - db-postgres-dev
    networks:
      - gearglobe-dev

  db-postgres-dev:
    image: postgres:16
    container_name: gearglobe_db_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gearglobe_db
      POSTGRES_USER: gearglobe
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - gearglobe-dev

  portainer-dev:
    image: portainer/portainer-ce:2.21.3
    container_name: gearglobe_portainer_dev
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data_dev:/data
    networks:
      - gearglobe-dev

networks:
  gearglobe-dev:
    driver: bridge

volumes:
  postgres_data_dev:
  portainer_data_dev: