spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    user:
      name: user
      password: pass
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG