openapi: 3.0.0
info:
  title: Gear Globe API
  description: Gear Globe API
  version: 1.0.0
tags:
  - name: Offer
    description: Offer API
  - name: Client
    description: Client API
servers:
  - url: http://localhost:8080


paths:
  /api/offers/cars:
    get:
      tags:
        - Offer
      summary: Get all car offers
      operationId: getAllCarOffers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/CarOfferResponse'
  /api/offers:
    post:
      tags:
        - Offer
      summary: Create offer
      operationId: createOffer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOfferRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferIdResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/offers/{id}:
    get:
      tags:
        - Offer
      summary: Get offer by ID
      operationId: getOfferById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - Offer
      summary: Update offer by ID
      operationId: updateOfferById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOfferRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Offer
      summary: Archive offer by ID
      operationId: archiveOfferById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferIdResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/clients:
    get:
      tags:
        - Client
      summary: Get all clients
      operationId: getAllClients
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClientResponse'
    post:
      tags:
        - Client
      summary: Create client
      operationId: createClient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClientRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/clients/{id}:
    get:
      tags:
        - Client
      summary: Get client by ID
      operationId: getClientById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - Client
      summary: Update client by ID
      operationId: updateClientById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClientRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Client
      summary: Deactivate client by ID
      operationId: deactivateClientById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientIdResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/clients/{id}/address:
    put:
      tags:
        - Client
      summary: Update client's address by ID
      operationId: updateClientAddress
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAddressRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/clients/{id}/password:
    patch:
      tags:
        - Client
      summary: Change client's password by ID
      operationId: changeClientPassword
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePasswordRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientIdResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    OfferResponse:
      type: object
      discriminator:
        propertyName: offerType
        mapping:
          CAR: '#/components/schemas/CarOfferResponse'
          BIKE: '#/components/schemas/BikeOfferResponse'
      properties:
        offerType:
          $ref: '#/components/schemas/OfferType'
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        negotiable:
          type: boolean
        createDate:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/OfferStatus'
    CarOfferResponse:
      allOf:
        - $ref: '#/components/schemas/OfferResponse'
        - type: object
          properties:
            make:
              type: string
            model:
              type: string
            body:
              $ref: '#/components/schemas/CarBodyType'
            version:
              type: string
            generation:
              type: string
            vin:
              type: string
            fuel:
              $ref: '#/components/schemas/FuelType'
            power:
              type: integer
            gearbox:
              $ref: '#/components/schemas/GearBox'
            insideCityFuelConsumption:
              type: number
              format: double
            outsideCityFuelConsumption:
              type: number
              format: double
            doorCount:
              type: integer
            color:
              type: string
            paintFinish:
              type: string
            productionCountry:
              type: string
            productionYear:
              type: integer
              format: int64
            isRegisteredInPoland:
              type: boolean
            isAfterIncident:
              type: boolean
            wearStage:
              $ref: '#/components/schemas/WearStage'
            millage:
              type: integer
              format: int64
            engineCapacity:
              type: number
              format: double
    BikeOfferResponse:
      allOf:
        - $ref: '#/components/schemas/OfferResponse'
        - type: object
          properties:
            bike:
              type: integer
              format: int64
    OfferIdResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
    CreateOfferRequest:
      type: object
      required:
        - offerType
        - title
        - description
        - price
        - negotiable
      discriminator:
        propertyName: offerType
        mapping:
          CAR: '#/components/schemas/CreateCarOfferRequest'
          BIKE: '#/components/schemas/CreateBikeOfferRequest'
      properties:
        offerType:
          $ref: '#/components/schemas/OfferType'
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        negotiable:
          type: boolean
    CreateCarOfferRequest:
      allOf:
        - $ref: '#/components/schemas/CreateOfferRequest'
        - type: object
          required:
            - make
            - model
            - body
            - version
            - generation
            - vin
            - fuel
            - power
            - gearbox
            - insideCityFuelConsumption
            - outsideCityFuelConsumption
            - doorCount
            - color
            - productionYear
            - isRegisteredInPoland
            - isAfterIncident
            - wearStage
            - millage
            - engineCapacity
          properties:
            make:
              type: string
            model:
              type: string
            body:
              $ref: '#/components/schemas/CarBodyType'
            version:
              type: string
            generation:
              type: string
            vin:
              type: string
            fuel:
              $ref: '#/components/schemas/FuelType'
            power:
              type: integer
            gearbox:
              $ref: '#/components/schemas/GearBox'
            insideCityFuelConsumption:
              type: number
              format: double
            outsideCityFuelConsumption:
              type: number
              format: double
            doorCount:
              type: integer
            color:
              type: string
            paintFinish:
              type: string
            productionCountry:
              type: string
            productionYear:
              type: integer
              format: int64
            isRegisteredInPoland:
              type: boolean
            isAfterIncident:
              type: boolean
            wearStage:
              $ref: '#/components/schemas/WearStage'
            millage:
              type: integer
              format: int64
            engineCapacity:
              type: number
              format: double
    CreateBikeOfferRequest:
      allOf:
      - $ref: '#/components/schemas/CreateOfferRequest'
      - type: object
        properties:
          test:
            type: string
    UpdateOfferRequest:
      type: object
      properties:
        mark:
          type: string
        productionYear:
          type: integer
          format: int64
        millage:
          type: integer
          format: int64
        engineCapacity:
          type: number
          format: double
        description:
          type: string
        price:
          type: number
          format: double
    ClientResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        lastName:
          type: string
        clientType:
          $ref: '#/components/schemas/ClientType'
        birthDate:
          type: string
          format: date
        email:
          type: string
        phoneNumber:
          type: string
        address:
          $ref: '#/components/schemas/AddressResponse'
        clientRole:
          $ref: '#/components/schemas/ClientRole'
        clientStatus:
          $ref: '#/components/schemas/ClientStatus'
    ClientIdResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
    CreateClientRequest:
      type: object
      required:
        - name
        - clientType
        - email
        - phoneNumber
        - address
        - password
      properties:
        name:
          type: string
          pattern: '^[a-zA-Z\p{L}]+([ .-][.a-zA-Z\p{L}]+)*$'
        lastName:
          type: string
          pattern: '^[a-zA-Z\p{L}]+([ -][a-zA-Z\p{L}]+)*$'
        clientType:
          $ref: '#/components/schemas/ClientType'
        birthDate:
          type: string
          format: date
        email:
          type: string
          pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        phoneNumber:
          type: string
          pattern: '^\d{9}$'
        address:
          $ref: '#/components/schemas/CreateAddressRequest'
        password:
          type: string
    UpdateClientRequest:
      type: object
      required:
        - name
        - clientType
        - email
        - phoneNumber
      properties:
        name:
          type: string
          pattern: '^[a-zA-Z\p{L}]+([ .-][.a-zA-Z\p{L}]+)*$'
        lastName:
          type: string
          pattern: '^[a-zA-Z\p{L}]+([ -][a-zA-Z\p{L}]+)*$'
        clientType:
          $ref: '#/components/schemas/ClientType'
        birthDate:
          type: string
          format: date
        email:
          type: string
        phoneNumber:
          type: string
    AddressResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        city:
          type: string
        street:
          type: string
        houseNumber:
          type: string
        apartmentNumber:
          type: string
        country:
          type: string
    CreateAddressRequest:
      type: object
      required:
        - city
        - street
        - houseNumber
        - country
      properties:
        city:
          type: string
        street:
          type: string
        houseNumber:
          type: string
        apartmentNumber:
          type: string
        country:
          type: string
    UpdateAddressRequest:
      type: object
      required:
        - city
        - street
        - houseNumber
        - country
      properties:
        city:
          type: string
        street:
          type: string
        houseNumber:
          type: string
        apartmentNumber:
          type: string
        country:
          type: string
    UpdatePasswordRequest:
      type: object
      required:
        - oldPassword
        - newPassword
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
    OfferType:
      type: string
      enum:
        - CAR
        - BIKE
    OfferStatus:
      type: string
      enum:
        - ACTIVE
        - ARCHIVE
    CarBodyType:
      type: string
      enum:
        - SEDAN
        - COUPE
        - HATCHBACK
        - SUV
        - CROSSOVER
        - WAGON
        - PICKUP_TRUCK
        - VAN
    FuelType:
      type: string
      enum:
        - GASOLINE
        - GASOLINE_LPG
        - DIESEL
        - ELECTRIC
        - HYBRID
    GearBox:
      type: string
      enum:
        - MANUAL
        - AUTOMATIC
    WearStage:
      type: string
      enum:
        - NEW
        - USED
        - BROKEN
    ClientStatus:
      type: string
      enum:
        - ACTIVE
        - INACTIVE
        - SUSPENDED
    ClientType:
      type: string
      enum:
        - PERSON
        - COMPANY
    ClientRole:
      type: string
      enum:
        - CLIENT
        - ADMIN
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string